### ISSUE TITLE
startpagina | contactknop springt niet

### ISSUE THREAD

**Issue by lentekindvakantiewerking** [anneliesvanminsel/www.lentekindvakantiewerking.be#7]
**Beschrijving van de issue**
Als ik op de startpagina bovenaan op 'contact' druk, verspringt hij niet automatisch naar de contactgegevens wat hij bij 'lentekindjes' en 'over lentekind' wel doet.

**Zo ben je de issue tegen gekomen**
startpagina

Stappen om de issue tegen te komen:
gewoon op de startpagina

**Wat verwacht je dat zou gebeuren?**
Als ik daarop druk zou ik verwacht dat het scherm verspringt naar onder naar de contactgegevens

**Screenshots**
Als het mogelijk is, geef een screenshot mee.
![image](https://user-images.githubusercontent.com/49321946/56474616-74371500-647c-11e9-9da3-f651e95c68ee.png)

**Device**
Chrome

**Extre informatie**

**Comment by anneliesvanminsel** [comment]
Copy van andere issue. Wordt gesloten!
